######################################################################
##
## Filename: tb_BIN2BCD.udo
## Created on: Mon Apr 25 21:13:43 Mitteleuropäische Sommerzeit 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
