######################################################################
##
## Filename: tb_counter.udo
## Created on: Mon Apr 25 19:27:15 Mitteleuropäische Sommerzeit 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
