######################################################################
##
## Filename: tb_teilcounter.udo
## Created on: Tue Apr 12 15:36:41 Mitteleuropäische Sommerzeit 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
