######################################################################
##
## Filename: tb_vergleicher.udo
## Created on: Tue Apr 12 16:05:45 Mitteleuropäische Sommerzeit 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
